steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - get_date
      - --region=us-central1
      - --trigger-http
      - --source=./cloudfunctions
      - --runtime=python38
      - --entry-point=get_date
      - --service-account=rnd-cf@utility-unity-377912.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --max-instances=5
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions 
      - add-iam-policy-binding
      - get_date
      - --region=us-central1
      - --member=allUsers
      - --role=roles/cloudfunctions.invoker
